export const SERVER_UPDATE_ACCOUNTS = "SERVER_UPDATE_ACCOUNTS";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";
export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";
